### ISSUE TITLE
Appearance form error when submitting after uploading Interior Page logo 

### ISSUE THREAD

**Issue by ashooner** [uky-web-archive/seeblue#3]
File (png) uploads successfully via ajax, but on form submit, this error is returned, and the file field content is not saved:

Notice: Undefined index: logo in seeblue_settings_submit() (line 216 of /var/www/html/drupal723/sites/www.uky.edu.provost/themes/seeblue/theme-settings.php).

**Comment by cornettims** [comment]
Is this resolved with the custom module (outside the theme) that includes the php source file? This issue is the submit function in the .inc included by the module is not running.

**Comment by ashooner** [comment]
I don't think so, dib.uky.edu/provost does have that module activated.

**Comment by cornettims** [comment]
I think this might be in theme-settings.php then -- that was updated with a commit a moment ago.

**Comment by ashooner** [comment]
ddb9bef fixes the error, but logo is still not being used. I'll create a new issue.
